FROM python:3.10 

RUN pip install paho-mqtt
# Install the Docker client
# RUN apt-get update && \
#     apt-get -y install apt-transport-https ca-certificates curl gnupg lsb-release && \
#     curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
#     echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
#     $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
#     apt-get update && \
#     apt-get -y install docker-ce-cli

# # Set up the necessary permissions
# RUN groupadd docker && \
#     usermod -aG docker $USER && \
#     chgrp docker /usr/bin/docker && \
#     chmod +s /usr/bin/docker

COPY matchmaker.py /app/matchmaker.py
COPY room.py /app/room.py

WORKDIR /app
CMD ["python", "-u", "matchmaker.py"]