FROM python:3.10 

RUN pip install paho-mqtt

# Install the Docker client
RUN apt-get update && apt-get install -y docker.io

COPY matchmaker.py /app/matchmaker.py
COPY room/room.py /app/room.py
COPY room/dockerfile /app/dockerfile

WORKDIR /app
CMD ["python", "-u", "matchmaker.py"]